baseURL = "https://www.defichain.com/"
googleAnalytics = "UA-145606297-3"
languageCode = "en-us"
title = "DeFiChain"

[params]
  uen = "201918368M"
  [params.featured]
    headline = "_Liquidity mine_ at more than 100% APR, _DEX_ is live."
  [params.featured.cta]
    label = "Learn more"
    url = "/dex"
  [params.github]
    label = "GitHub"
    url = "https://github.com/DeFiCh/ain"
    releases_url = "https://github.com/DeFiCh/ain/releases"
  [params.social]
    facebook = "https://facebook.com/cakedefi/"
    twitter = "https://twitter.com/cakedefi"
    reddit = "https://reddit.com/r/cakedefi/"
    youtube = "https://www.youtube.com/channel/UCkRa0RHkJ9Udd_mVWl8fa8A"
    telegram = "https://t.me/CakeDeFi_EN"
  [params.exchanges]
    [[params.exchanges.list]]
      label = "KuCoin"
      url = "https://trade.kucoin.com/DFI-BTC"
      file = "/svg/sources/logo-kucoin"
      type = "svg"
    [[params.exchanges.list]]
      label = "Bittrex"
      url = "https://global.bittrex.com/Market/Index?MarketName=BTC-DFI"
      file = "/svg/sources/logo-bittrex"
      type = "svg"
    [[params.exchanges.list]]
      label = "LATOKEN"
      url = "https://go.latoken.com/1gd"
      file = "/svg/sources/logo-latoken"
      type = "svg"
    # [[params.exchanges.list]]
    #   label = "Coinpaprika"
    #   url = "https://coinpaprika.com/coin/dfi-defi-chain/"
    #   file = "/svg/sources/logo-coinpaprika"
    #   type = "svg"
    # [[params.exchanges.list]]
    #   label = "CoinGecko"
    #   url = "https://www.coingecko.com/en/coins/defichain"
    #   file = "/svg/sources/logo-coingecko"
    #   type = "svg"
    [[params.exchanges.list]]
      label = "Hotbit"
      url = "https://www.hotbit.io/exchange?symbol=DFI_USDT"
      file = "/img/sources/logo-hotbit"
      type = "png"
    [[params.exchanges.list]]
      label = "Bittrue"
      url = "https://www.bitrue.com/trade/dfi_btc"
      file = "/svg/sources/logo-bittrue"
      type = "svg"
    [[params.exchanges.list]]
      label = "EasyCrypto (AU)"
      url = "https://easycrypto.ai/au/buy-sell/dfi-defichain"
      file = "/img/sources/logo-easycrypto-au"
      type = "png"
    [[params.exchanges.list]]
      label = "EasyCrypto (NZ)"
      url = "https://easycrypto.ai/nz/buy-sell/dfi-defichain"
      file = "/img/sources/logo-easycrypto-nz"
      type = "png"
  [params.menu]
    social = "Social"
    buy_dfi = "Buy $DFI"
    downloads = "Downloads"
    twitter = "Twitter"
    youtube = "YouTube"
    reddit = "Reddit"
    telegram = "Telegram"
    linkedin = "LindedIn"
    facebook = "Facebook"
    github = "GitHub"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[blackfriday]
  extensions = ["hardLineBreak"]

DefaultContentLanguage = "en"
staticDir = ["static1", "static2"]

[languages]
  [languages.en]
    baseURL = "https://www.defichain.com/"
    staticDir2 = "static_en"
    contentDir = "content/en"
    languageName = "English"
    title = "DeFiChain"
    description = "Decentralized finance enabled on Bitcoin."
    company_name = "DeFiChain"
    copyright = "All Rights Reserved"
    weight = 20
  [languages.zh-hans]
    baseURL = "https://www.zh.defichain.com/"
    staticDir = ["staticDir_override", "static_zh-hans"]
    contentDir = "content/zh-hans"
    languageName = "简体中文"
    title = "DeFiChain"
    description = "官方中文网递飞链"
    company_name = "DeFiChain"
    copyright = "All Rights Reserved"
    weight = 30
    [languages.zh-hans.params.featured]
      headline = "_DEX_ 已启动并开放超过100％年利率的 _流动性矿池_"
    [languages.zh-hans.params.featured.cta]
      label = "了解更多"
      url = "/dex"
    [languages.zh-hans.params.github]
      label = "GitHub源代码"
      url = "https://github.com/DeFiCh/ain"
      releases_url = "https://github.com/DeFiCh/ain/releases"
    [languages.zh-hans.params.menu]
      social = "社区"
      buy_dfi = "购买 $DFI"
      downloads = "下载中心"
      twitter = "推特"
      youtube = "YouTube"
      reddit = "Reddit"
      telegram = "电报群"
      linkedin = "領英"
      facebook = "脸书"
      github = "GitHub源代码"
  # [languages.zh-hant]
  #   contentDir = "content/zh-hant"
  #   languageName = "繁體中文"
  #   title = "DeFiChain"
  #   description = "官方中文網遞飛鏈"
  #   company_name = "DeFiChain"
  #   copyright = "All Rights Reserved"
  #   weight = 40
  #   [languages.zh-hant.params.featured]
  #     headline = "_DEX_ 已啟動並開放超過100%年利率的 _流動性礦池_"
  #   [languages.zh-hant.params.featured.cta]
  #     label = "了解更多"
  #     url = "/dex"
  #   [languages.zh-hant.params.github]
  #     label = "GitHub源代碼"
  #     url = "https://github.com/DeFiCh/ain"
  #     releases_url = "https://github.com/DeFiCh/ain/releases"
  #   [languages.zh-hant.params.menu]
  #     social = "社區"
  #     buy_dfi = "購買 $DFI"
  #     downloads = "下載中心"
  #     twitter = "推特"
  #     youtube = "YouTube"
  #     reddit = "Reddit"
  #     telegram = "電報群"
  #     linkedin = "領英"
  #     facebook = "臉書"
  #     github = "GitHub源代碼"
  # [languages.de]
  #   languageName = "Deutsch"
  #   title = "DeFiChain"
  #   description = "Making the world a brighter place"
  #   company_name = "Cake Pte. Ltd."
  #   copyright = "Alle Rechte vorbehalten"
  #   fast_track = "Fast-track"
  #   weight = 30
